#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

export XKL_XMODMAP_DISABLE=1
export DISPLAY=:1

# Start dbus session
eval $(dbus-launch --sh-syntax --exit-with-session) 2>/dev/null || true

xsetroot -solid "#2d2d2d" &

# Start XFCE4
exec startxfce4
